name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: crystal-lang/install-crystal@v1
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y zlib1g-dev
      - run: make
      - run: make test
      - run: bin/fqix --version
